### ISSUE TITLE
Faraday default adapter capitalize headers and makes requests broken for some APIs

### ISSUE THREAD

**Issue by matuszewskijan** [winebarrel/faraday_middleware-aws-sigv4#14]
Hi, thank you for the awesome work on this Gem. It saved me a lot of time while developing connection with Amazon Selling Partner API.

There is one tricky thing I think we could mention in the Readme - in the `SP API` we have to send `x-amz-access-token` in request headers. This header is for some reason case sensitive. I've lost few hours getting `Access Denied` error until I found out that Faraday default adapter `Net::HTTP` capitalizes header names by default: https://github.com/lostisland/faraday/issues/747#issuecomment-439864181

Once I've switched the adapter to `excon` adapter it just started working.

Wanted to add such comment in the Readme to probably save some time for someone else meeting this problem in future:
```
  ...
  faraday.response :json, content_type: /\bjson\b/
  faraday.response :raise_error

  # NOTE: If you need to send case sensitive headers like `x-amz-access-token` in `SP API` I strongly
  # recommend you don't use the default Net::HTTP adapter as it's capitalizing header names:
  # https://github.com/lostisland/faraday/issues/747#issuecomment-439864181
  faraday.adapter Faraday.default_adapter
end
```

Don't have access to open a pull request so writing it as an issue.

**Comment by winebarrel** [comment]
Thank you 😃 
Added a comment at https://github.com/winebarrel/faraday_middleware-aws-sigv4/pull/16
