### ISSUE TITLE
Confirm Ruby 3 support

### ISSUE THREAD

**Issue by hatricker** [winebarrel/faraday_middleware-aws-sigv4#24]
As Ruby 2.7 EOL is supposed to be end of March 2023, would you be able to confirm Ruby 3 compatibility? Thanks.

**Comment by winebarrel** [comment]
Ruby 3.x tests have passed.
see https://github.com/winebarrel/faraday_middleware-aws-sigv4/blob/09367bd5e26ee6a6a9af24c7c08b5cf7be22e799/.github/workflows/test.yml#L15-L17
