### ISSUE TITLE
[Question]Why is faraday_middleware a development dependency?

### ISSUE THREAD

**Issue by toshimaru** [winebarrel/faraday_middleware-aws-sigv4#3]
Although `require faraday_middleware` is required according to [usage document](https://github.com/winebarrel/faraday_middleware-aws-sigv4/blob/master/README.md#usage), why is its dependency is `development_dependency`? I'm wondering why `faraday_middleware` is not a runtime dependency.

**Comment by winebarrel** [comment]
This is because faraday_middleware is **not required**.
Please execute the following code:
https://gist.github.com/winebarrel/9c72a245e0469c3011e3809f831de3ef

The sample code uses faraday_middleware because I think that faraday_middleware is often used with faraday_middleware-aws-sigv4.

**Comment by toshimaru** [comment]
> The sample code uses faraday_middleware because I think that faraday_middleware is often used with faraday_middleware-aws-sigv4.

Now, I get it. Thanks 👍
