### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by olleolleolle** [winebarrel/faraday_middleware-aws-sigv4#35]
❤️ Thank you for supporting Faraday 2! ❤️ 

I would like to use this in the rubygems.org website, since then we could go all the way to Faraday 2+ there.

If you need anything to make a release, just ask! (I could write a changelog, celebrate, or otherwise cheer on!)

# Changes since last release v1.0.1.

https://github.com/winebarrel/faraday_middleware-aws-sigv4/compare/v1.0.1...master

**Comment by winebarrel** [comment]
Hello 😃 

Changes to `v1.0.1...master` are only for testing and modifying the CI environment, there are no changes to the library itself.
So I think v1.0.1 already supports Faraday 2+.

Could you please let me know if you are having problems with faraday_middleware-aws-sigv4 v1.0.1+Faraday 2+?

**Comment by olleolleolle** [comment]
you are absolutely right, and the version that I was looking at was faraday_middleware-aws-sigv4 (0.6.1)! Supe!
